# Generated by Django 2.1.4 on 2019-01-07 10:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_auto_20190107_1424'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Logon',
        ),
        migrations.DeleteModel(
            name='Password',
        ),
    ]
