# Generated by Django 2.1.4 on 2019-01-04 12:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='songs',
            new_name='song',
        ),
    ]
