swagger: "3.0"
info:
  description: "This is a sample server."
  version: "1.0.0"
  title: "Swagger Application"
summary: "summary GET"
description: "description GET"
operationId: "_view_function"
consumes:
  - "application/json"
  - "application/text"
produces:
  - "application/json"
  - "application/xml"
parameters:
- in: "path"
  name: "path"
  description: "Returns data"
#  required: true
#  type: "string"
responses:
  405:
    description: "Invalid input"
  200:
    description: 'successful operation'
  400:
    description: 'Invalid ID supplied'
  404:
    description: 'Id not found'
x-swagger-router-controller: '__Flask.SwaggerApp.swagger_python_flask_app'







































#swagger: '3.0'
#host: 'http://127.0.0.1:8080'
#basePath: '/'
##schemes:
##  - 'https'
##  - 'http'
#paths:
#  /hello-get:
#    get:
#      summary: "Returning function"
#      description: "Returns bye"
#      operationId: "get_numbers"
##      consumes:
##        - "application/json"
##        - "application/text"
##      produces:
##        - "application/json"
#    #    - "application/xml"
##      parameters:
##        - in: "path"
##          name: "path"
##          description: "Returns a BYE"
##          required: true
##          type: "string"
#      responses:
#        405:
#          description: "Invalid input"
#        200:
#          description: 'successful operation'
#        400:
#          description: 'Invalid ID supplied'
#        404:
#          description: 'Id not found'
#      x-swagger-router-controller: '__Flask.SwaggerApp.swagger_python_flask_app'