swagger: "3.0"
info:
  description: "This is a sample server."
  version: "1.0.0"
  title: "Swagger Application"
summary: "summary PUT"
description: "description PUT"
operationId: "_update_function"
consumes:
- "application/json"
- "application/text"
produces:
- "application/json"
- "application/xml"
parameter:
- in: "body"
  name: "body"
  description: "Accepts a input dictionary of inputs 'name' and 'location'"
  schema:
    - type: "object"
    properties:
    - name: "phone_no"
      in: "formData"
      description: "Updated phone_no of the person"
      required: True
      type: "integer"
      example: 8600003771
    - name: "pan_no"
      in: "formData"
      description: "Updated pan_no of the person"
      required: True
      type: "string"
      example: "AYHPK4348P"
responses:
  405:
    description: "Invalid input"
  200:
    description: 'successful operation'
  400:
    description: 'Invalid ID supplied'
  404:
    description: 'Id not found'
x-swagger-router-controller: '__Flask.SwaggerApp.swagger_python_flask_app'