# Generated by Django 2.1.4 on 2019-01-10 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0002_auto_20190110_1357'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='name',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
